# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2004, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.
#
# $Id: Makefile 1655 2009-11-03 23:42:49Z Herben $


SUBDIRS = tcpip tcpip131 tcpips udptty dns

include $(PS2SDKSRC)/Defs.make
include $(PS2SDKSRC)/Rules.make


